DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

-- para probar de la database --

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES (48270321, 'Carlos', 'Rodriguez'), (55555222, 'Perla', 'Blanco');