--tabla Domicilios
DROP TABLE IF EXISTS DOMICILIOS;

CREATE TABLE DOMICILIOS(ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(100) NOT NULL, PROVINCIA VARCHAR(100) NOT NULL);


-- tabla Odontólogos
DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);


-- tabla Pacientes
DROP TABLE IF EXISTS PACIENTES;

CREATE TABLE PACIENTES(ID INT AUTO_INCREMENT PRIMARY KEY,NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA DATE NOT NULL, DOMICILIO_ID INT);





-- para probar de la database --
INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Bvar San Francisco' , 123, 'San Francisco', 'San Francisco City')

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES (48270321, 'Carlos', 'Rodriguez'), (55555222, 'Perla', 'Blanco');

INSERT INTO PACIENTES(NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Juan', 'López', '123455', '2023-06-06', 1), ('Juana', 'López', '334455', '2023-06-06', 1)

--Esta línea asegura que el campo DOMICILIO_ID en la tabla PACIENTES siempre apunte a un registro válido en la tabla DOMICILIOS--
ALTER TABLE PACIENTES
ADD FOREIGN KEY (DOMICILIO_ID) REFERENCES DOMICILIOS(ID);